### ISSUE TITLE
Use += in python

### ISSUE THREAD

**Issue by pauser0000001** [bddicken/languages#101]
In python, using += 
 ```
   a[i] += j%u        # Simple sum
 a[i] += r
```
makes the code run in 3/4 times the original speed, and also increases pypy speed.

**Comment by t3rn0** [comment]
Yeah, it could be written something like that:
```
a = [sum(j % u for j in range(100000)) + r for _ in range(10000)]
print(a[r])
```
It's still slow anyway :)

**Comment by aqeelat** [comment]
@t3rn0 this would actually be slower than a regular for loop. I saw someone on twitter go in depth about it but I don't remember the argument exactly, but it was I think two orders of magnitude slower

**Comment by aqeelat** [comment]
@pauser0000001 it was a lot slower when I did this (84.12s vs 78.37s) on python 13.
However, when I generated the pyc for the original code, I got it down to 70.19s

**Comment by bddicken** [comment]
This should be a PR, rather than an issue.

**Comment by jsonn** [comment]
@pauser0000001 I said "function", not "comprehension". Please just try moving everything into a function scope. That helps because access to variables in local scopes is optimized and doesn't require a full hash table lookup like when using the global/module scope.
