### ISSUE TITLE
Your result for C is WRONG !!!

### ISSUE THREAD

**Issue by SinisaMil** [bddicken/languages#113]
Hi,

I have rewritten your C example in C 2017 standard.

I passed the argument 40 (forty) to the program. 

It executed on MacBook Air 15 " with M3 in 5 MICROSECONDS !!!!!!!!!

If you want me to send you code, please write to sinisa@cytanet.com.cy

**Comment by jrosell** [comment]
Oh boy, make a PR.

**Comment by guibranco** [comment]
@SinisaMil send your code via Pull request...

**Comment by SinisaMil** [comment]
Actually, the above result is wrong.

I have changed my program and it runs with a speed between 20 and 45 microseconds .....

I am now adding my code via pull request .....


DO NOT USE /usr/bin/time PROGRAM !!!!!

My program calculates the speed itself !!!!!!!

You should compile it with gcc or clang, with the options like this: 

gcc -O3 -fomit-frame-pointer -Wall -o  test test.c

You can run it without arguments, in which case a default value of 40 would be used.

DO NOT USE /usr/bin/time PROGRAM !!!!!

My program calculates the speed itself !!!!!!!

I am now sending my code via pull request.

**Comment by SinisaMil** [comment]
Pull requests do not work for me. Here is my code:

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <inttypes.h>
#include <time.h>


int main (int argc, char **argv) {
  clock_t ttt= clock();
  register uint32_t u=  (argc > 1) ? (uint32_t) atoi(argv[1]) : 40;
  register uint32_t r= (uint32_t) (rand() % 10000);
  uint32_t a[10000]= {0};
  double time_taken;


  for (register uint16_t i= 0; i < 10000; i++) {
    for (register uint32_t j= 0; j< 100000; j++) {
      a[i]= a[i] + (j % u);
    }
    a[i]= r;
  }
  printf("%d\n", a[r]);
  ttt= clock() - ttt;
  time_taken = ((double)ttt*1000000.0)/((double)CLOCKS_PER_SEC); // in microseconds
  printf("Search speed = %f microseconds  \n\n\n", time_taken);
  return 0;
}

**Comment by jrosell** [comment]
> Actually, the above result is wrong.
> 
> I have changed my program and it runs with a speed between 20 and 45 microseconds .....
> 
> I am now adding my code via pull request .....
> 
> DO NOT USE /usr/bin/time PROGRAM !!!!!
> 
> My program calculates the speed itself !!!!!!!
> 
> You should compile it with gcc or clang, with the options like this:
> 
> gcc -O3 -fomit-frame-pointer -Wall -o test test.c
> 
> You can run it without arguments, in which case a default value of 40 would be used.
> 
> DO NOT USE /usr/bin/time PROGRAM !!!!!
> 
> My program calculates the speed itself !!!!!!!
> 
> I am now sending my code via pull request.

Related https://github.com/bddicken/languages/issues/98

**Comment by NoxMaw** [comment]
> Pull requests do not work for me. Here is my code:
> 
> #include <stdio.h> #include <stdlib.h> #include <stdint.h> #include <inttypes.h> #include <time.h>
> 
> int main (int argc, char **argv) { clock_t ttt= clock(); register uint32_t u= (argc > 1) ? (uint32_t) atoi(argv[1]) : 40; register uint32_t r= (uint32_t) (rand() % 10000); uint32_t a[10000]= {0}; double time_taken;
> 
> for (register uint16_t i= 0; i < 10000; i++) { for (register uint32_t j= 0; j< 100000; j++) { a[i]= a[i] + (j % u); } a[i]= r; } printf("%d\n", a[r]); ttt= clock() - ttt; time_taken = ((double)ttt*1000000.0)/((double)CLOCKS_PER_SEC); // in microseconds printf("Search speed = %f microseconds \n\n\n", time_taken); return 0; }

I edited your code a little bit, mostly for clarity. Also, since printf is a slow function, switched it for a manual loop using putchar();
```c
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
//We are including time.h here for the clock(); function
#include <time.h>

int main (int argc, char **argv) {
	/**
	 * Define clock start time and time taken to measure the time
	 * After the loop is finished.
	 */
	clock_t start_time = clock(); // Start counting time
    double time_taken;
    

	/** 
	 * Get an input from the command like or use a default
	 * value of 40. This adds a single extra computation
	 * but it should be fine.
	 */ 
	register uint32_t u = (argc > 1) ? (uint32_t)atoi(argv[1]) : 40;

	// Get a random unsigned integer 0 <= r < 10k
	register uint32_t r = (uint32_t)(rand() % 10000);
	
	// Array of 10k elements initialized to 0
	uint32_t a[10000] = {0};

	// 10k outer loop iterations
	for (register uint16_t i= 0; i < 10000; i++) {
		// 100k inner loop iterations, per outer loop iteration
		for (register uint32_t j= 0; j< 100000; j++) {
		    // "Simple sum" is actually using modulo lol
			a[i] += (j % u);
		}
		// The original function uses += instead of =, fixed this
		// Add a random value to each element in array
		a[i] += r;
	}

	//Print the integer and a newline
	char buffer[12]; // Enough to store a 32-bit signed integer
    int x = 0;

    while (a[r] > 0) {
        buffer[x++] = (a[r] % 10) + '0';
        a[r] /= 10;
    }
    while (x--) {
        putchar(buffer[x]);
    }
    putchar('\n');
	
	// Calculate and print the time taken in microseconds
	start_time= clock() - start_time;
	time_taken = ((double)start_time*1000000.0)/((double)CLOCKS_PER_SEC);
	printf("Search speed = %f microseconds \n\n\n", time_taken);
	return 0;
}
```

**Comment by SinisaMil** [comment]
Thank you .......

But, in any case, the value of 0.5 seconds for a well written program in C is a TOTAL nonsense !!!!

**Comment by SinisaMil** [comment]
Thank you, NoxMaw,

However your "beautifying" of my code resulted in SO MANY errors .......

Did you try to run it ????

Even on my old  Intel i3 on iMac from 2018, my program runs in 18 microseconds  ...... 

Your "version" runs 100 times slower ....... 

You simply made too many mistakes and "code improvements " that slow down everything .....

**Comment by bddicken** [comment]
If you'd like this included, please make a PR.
