### ISSUE TITLE
PHP is not using JIT

### ISSUE THREAD

**Issue by realFlowControl** [bddicken/languages#17]
Hey there 👋 

in the example PHP is not using the JIT compiler, this is due to the OPcache being default disabled on CLI and the JIT (as part of OPcache) also being default disabled. Would you be interested in a PR?
I am not sure how you install PHP and if the OPcache extension (which is part of core PHP) is present and enabled, you could help me with running `php -m` and see if there is a `Zend OPcache` extension listed.
I can submit a PR if you like.

**Comment by vishrutkmr7** [comment]
https://github.com/bddicken/languages/pull/19

**Comment by bddicken** [comment]
A jit option has been added!
