### ISSUE TITLE
Why isn't C# AOT compiled?

### ISSUE THREAD

**Issue by q0v0p** [bddicken/languages#170]
Why is C# included in the benchmarks even though it doesn't use AOT compilation?

![image](https://github.com/user-attachments/assets/c5fc1d63-7b1b-4a93-ad0f-e790d59b27b6)

**Comment by cordasfilip** [comment]
I think there is a lot to improve here unsafe add and vectors for simd https://www.youtube.com/watch?v=mSBsWBKh1-k

**Comment by MichalStrehovsky** [comment]
The maintainer dropped the AOT flavor as part of "tweaks" here: https://github.com/bddicken/languages/commit/bf71f98f0a823775c16fdb79f2445438f471edf6

Maintainer did the same for Java (GraalVM native image).

I couldn't find the motivation anywhere in this repo. Java and C# are only going to perform well for a startup sensitive workload like this with AOT.

**Comment by bddicken** [comment]
Someone submitted a PR for an AOT update 👍
