### ISSUE TITLE
loop does 10,000x too much work

### ISSUE THREAD

**Issue by Spongman** [bddicken/languages#274]
it fills the array with 10,000 values, and only uses one.

the following C code is equivalent, and runs 10,000 times faster.

```
int main(int argc, char** argv) {
  int u = atoi(argv[1]);
  srand(time(NULL));
  int r = rand() % 10000;
  int a = 0;
  for (int j = 0; j < 100000; j++) {
    a = a + j % u;
  }
  a += r;
  printf("%d\n", a);
}
```

**Comment by Spongman** [comment]
actually, scratch that. the whole thing is reducible to
```
  int N = 100000-1;
  printf("%d\n", r + ((N / u) * u * (u - 1) + (N % u) * ((N % u) + 1)) / 2);
```

**Comment by PEZ** [comment]
The benchmark is referred to as **1 Billion nested loop iterations** for a reason.

**Comment by zierf** [comment]
@Spongman has a valid point here. Some compilers could reduce the problem partially or even completely.

That contradicts statements like this [Comment in Issue #229](https://github.com/bddicken/languages/issues/229#issuecomment-2530099303)
> The loops test is not about calculating the same answer, but doing the same amount of "work" and seeing how languages perform doing that work.

@PEZ If it's about doing the "same work" and in this case with loops, the problem should force the language doing all the iterations. Some languages could reduce the problem like stated in the second comment and then there are no loops measured.

Furthermore calculating random numbers and modulo is different across languages. I believe Casey mentioned once a trap by calculating modulo like this specifically in C and that there were safer implementations.

Right now it's more about measuring the random number generator (with many different default implementations) and modulo calculation, not so much about measuring the actual loops.
Although measuring the loops itself should be fast across all languages and has no real value.

**Comment by Spongman** [comment]
yeah, @PEZ you completely missed my point.

the code is clearly attempting to do irreducible work. and it fails - the computation is reducible to O(1) for ALL inputs.
