### ISSUE TITLE
Can U add .NET/C#?

### ISSUE THREAD

**Issue by wildtang** [bddicken/languages#37]
Especially .NET Core 8+, Thanks.

**Comment by sannlynnhtun-coding** [comment]
Would it be possible to add .NET 9 for C# developers? Thanks!

**Comment by vtnorton** [comment]
There is a PR that solves this 
https://github.com/bddicken/languages/pull/25

**Comment by Odonno** [comment]
Would like some code reviews for this PR https://github.com/bddicken/languages/pull/21

**Comment by rugglcon** [comment]
Highly seconded

**Comment by bddicken** [comment]
C# added.
