### ISSUE TITLE
Initial problem update

### ISSUE THREAD

**Issue by cyrusmsk** [bddicken/languages#61]
Current problem for loops is pretty simple and it is easy to apply concurrency, vectorization, parallel, SIMD approach to boost the performance.

If you make each next step of the loop (N) dependent on previous results (k steps) with some randomness then it will be harder to apply simple rules for speed-ups and will eliminate possible hacks (at least some of them) :)

**Comment by cyrusmsk** [comment]
Also as a nice example you can check this bench: https://github.com/jinyus/related_post_gen

It has 2 types of code (simple and parallel/concurrent), specific rules (especially about safety checks, fast-math and other things) and precise hardware description (even though there are some issues with it, because clouds could provide different results as not real physical devices, but virtualization containers)

**Comment by bddicken** [comment]
I'd welcome additional benchmark programs.
